# Generated by Django 4.0.5 on 2022-06-20 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodoPago', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('ranking', models.PositiveSmallIntegerField()),
                ('precio', models.PositiveIntegerField()),
                ('stock', models.PositiveSmallIntegerField()),
                ('img', models.CharField(max_length=255)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.categoriaproducto')),
            ],
        ),
        migrations.CreateModel(
            name='Pyme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('montoTotal', models.PositiveIntegerField()),
                ('metodoPago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.metodopago')),
                ('productos', models.ManyToManyField(to='api.producto')),
                ('pyme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pyme')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('telefono', models.PositiveIntegerField()),
                ('email', models.CharField(max_length=60)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.categoriaproveedor')),
                ('pyme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pyme')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='pyme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pyme'),
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('precio', models.PositiveIntegerField()),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now=True)),
                ('montoTotal', models.PositiveIntegerField()),
                ('insumos', models.ManyToManyField(to='api.insumo')),
                ('pyme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pyme')),
            ],
        ),
        migrations.AddField(
            model_name='categoriaproveedor',
            name='pyme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pyme'),
        ),
        migrations.AddField(
            model_name='categoriaproducto',
            name='pyme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pyme'),
        ),
    ]
